### ISSUE TITLE
YAML exception on v0.5.2

### ISSUE THREAD

**Issue by santilococo** [CaramelFur/Picsur#61]
Hello, 

I got an error while attempting to use the `docker-compose.yml` file provided in the `README.md`. 

The error message I got is as follows:

```
picsur           | YAMLException: can not read an implicit mapping pair; a colon is missed at line 14674, column 6:
picsur           |         h
picsur           |          ^
picsur           |         h
picsur           |          ^
picsur           |     at AK (/picsur/.yarn/releases/yarn-berry.cjs:13:789)
picsur           |     at dt (/picsur/.yarn/releases/yarn-berry.cjs:13:891)
picsur           |     at Jhe (/picsur/.yarn/releases/yarn-berry.cjs:20:1500)
picsur           |     at ag (/picsur/.yarn/releases/yarn-berry.cjs:20:4422)
picsur           |     at Jhe (/picsur/.yarn/releases/yarn-berry.cjs:20:1775)
picsur           |     at ag (/picsur/.yarn/releases/yarn-berry.cjs:20:4422)
picsur           |     at Jhe (/picsur/.yarn/releases/yarn-berry.cjs:20:1775)
picsur           |     at ag (/picsur/.yarn/releases/yarn-berry.cjs:20:4422)
picsur           |     at Vhe (/picsur/.yarn/releases/yarn-berry.cjs:20:6569)
picsur           |     at gK (/picsur/.yarn/releases/yarn-berry.cjs:21:260)
```

I am using aarch64.

**Comment by santilococo** [comment]
Also, version 0.5.1 of the app works fine.
