### ISSUE TITLE
error: no pg_hba.conf entry for host "172.18.0.2", user "picsur", database "picsur", no encryption

### ISSUE THREAD

**Issue by topmask** [CaramelFur/Picsur#89]
[Nest] 34  - 06/05/2024, 4:25:49 AM   ERROR [ExceptionHandler] no pg_hba.conf entry for host "172.18.0.2", user "picsur", database "picsur", no encryption
error: no pg_hba.conf entry for host "172.18.0.2", user "picsur", database "picsur", no encryption
    at Parser.parseErrorMessage (/picsur/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/picsur/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/picsur/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/picsur/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (node:events:514:28)
    at addChunk (node:internal/streams/readable:545:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:495:3)
    at Readable.push (node:internal/streams/readable:375:5)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
(node:34) ExperimentalWarning: `--experimental-loader` may be removed in the future; instead use `register()`:
--import 'data:text/javascript,import { register } from "node:module"; import { pathToFileURL } from "node:url"; register("extensionless", pathToFileURL("./"));'
(Use `node --trace-warnings ...` to show where the warning was created)

```
services:
  picsur:
    image: ghcr.io/caramelfur/picsur:latest
    container_name: picsur
    ports:
      - '127.0.0.1:8563:8563'
    environment:
      PICSUR_HOST: '0.0.0.0'
      PICSUR_PORT: 8563

      PICSUR_DB_HOST: picsur_postgres
      PICSUR_DB_PORT: 5432
      PICSUR_DB_USERNAME: picsur
      PICSUR_DB_PASSWORD: picsur
      PICSUR_DB_DATABASE: picsur

      ## 
      PICSUR_ADMIN_PASSWORD: "dasds"

      ## 
      # PICSUR_JWT_SECRET: CHANGE_ME
      # PICSUR_JWT_EXPIRY: 7d

      ## 
      PICSUR_MAX_FILE_SIZE: 128000000
      ## No need to touch this, unless you use a custom frontend
      # PICSUR_STATIC_FRONTEND_ROOT: "/picsur/frontend/dist"

      ## Warning: Verbose mode might log sensitive data
      # PICSUR_VERBOSE: "true"
    restart: unless-stopped
  picsur_postgres:
    image: postgres:14-alpine
    container_name: picsur_postgres
    environment:
      POSTGRES_DB: picsur
      POSTGRES_PASSWORD: picsur
      POSTGRES_USER: picsur
    restart: unless-stopped
    volumes:
      - /mnt/data/download/picsur-data:/var/lib/postgresql/data
volumes:
  picsur-data:


```

**Comment by topmask** [comment]
If the data disk is mounted on another disk, an error will occur. The original configuration will not cause an error. I want to ask where the uploaded image data is stored. Can the path of the data disk be changed? My VPS has limited capacity.


```
    - /mnt/data/download/picsur-data:/var/lib/postgresql/data
    
    - /picsur-data:/var/lib/postgresql/data
```
